const healthTips = [
  "tips.drinkWater",
  "tips.walkDaily",
  "tips.eatFruitsVeg",
  "tips.shortBreaks",
  "tips.sleepSchedule",
  "tips.washHands",
  "tips.deepBreathing",
  "tips.limitSugaryDrinks",
  "tips.morningStretch",
  "tips.organizeWorkspace",
  "tips.noSkippingBreakfast",
  "tips.strengthTraining",
  "tips.mindfulEating",
  "tips.checkUps",
  "tips.takeStairs",
  "tips.limitScreenTime",
  "tips.wholeGrains",
  "tips.listenMusic",
  "tips.firstAid",
  "tips.planMeals",
  "tips.indoorPlants",
  "tips.sunscreen",
  "tips.gratitude",
  "tips.sunlight",
  "tips.socialConnections",
  "tips.declutterHome",
  "tips.newHobby",
  "tips.activeTransport",
  "tips.reusableBottle",
  "tips.laughOften"
];

export default healthTips;
